import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:http/http.dart' as http;

const navy = Color(0xff070b1c), blue = Color(0xff5978ff), purple = Color(0xffa65cff);
void main() => runApp(const TrustLensApp());

class Api {
  Api(this.token); final String? token;
 static String baseUrl = 'http://192.168.0.109:8000';
  Future<dynamic> request(String method, String path, [Map<String,dynamic>? body]) async {
    final headers={'Content-Type':'application/json',if(token!=null)'Authorization':'Bearer $token'};
    late http.Response r; final uri=Uri.parse('$baseUrl$path');
    try { r=method=='GET'?await http.get(uri,headers:headers).timeout(const Duration(seconds:12)):method=='DELETE'?await http.delete(uri,headers:headers).timeout(const Duration(seconds:12)):await http.post(uri,headers:headers,body:jsonEncode(body)).timeout(const Duration(seconds:12)); }
    catch (_) { throw Exception('Cannot reach TrustLens API. Check the backend and API address.'); }
    if(r.statusCode>=200&&r.statusCode<300) return r.body.isEmpty?null:jsonDecode(r.body);
    try { throw Exception(jsonDecode(r.body)['detail'] ?? 'Request failed'); } catch(e) { if(e is Exception) rethrow; throw Exception('Request failed (${r.statusCode})'); }
  }
}
class TrustLensApp extends StatelessWidget { const TrustLensApp({super.key}); @override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'TrustLens',theme:ThemeData(useMaterial3:true,brightness:Brightness.dark,colorScheme:ColorScheme.fromSeed(seedColor:blue,brightness:Brightness.dark),scaffoldBackgroundColor:navy),home:const Splash()); }
class Splash extends StatefulWidget { const Splash({super.key}); @override State<Splash> createState()=>_SplashState(); }
class _SplashState extends State<Splash>{ final storage=const FlutterSecureStorage(); Timer? timer; @override void initState(){super.initState(); timer=Timer(const Duration(milliseconds:900),() async {final t=await storage.read(key:'token'); if(mounted) Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>t==null?const AuthPage():Dashboard(token:t)));});} @override void dispose(){timer?.cancel();super.dispose();} @override Widget build(c)=>const Scaffold(body:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(Icons.shield_outlined,size:84,color:blue),Text('TrustLens',style:TextStyle(fontSize:34,fontWeight:FontWeight.bold)),Text('Think before you trust')])));}
class AuthPage extends StatefulWidget { const AuthPage({super.key}); @override State<AuthPage> createState()=>_AuthPageState(); }
class _AuthPageState extends State<AuthPage>{bool register=false, busy=false; final name=TextEditingController(),email=TextEditingController(),password=TextEditingController(),confirm=TextEditingController(); Future<void> submit() async {if(register&&password.text!=confirm.text){toast('Passwords do not match');return;} setState(()=>busy=true);try{final d=await Api(null).request('POST',register?'/api/auth/register':'/api/auth/login',register?{'name':name.text,'email':email.text,'password':password.text}:{'email':email.text,'password':password.text}); await const FlutterSecureStorage().write(key:'token',value:d['access_token']); if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>Dashboard(token:d['access_token'])));}catch(e){toast(e.toString());}finally{if(mounted)setState(()=>busy=false);}} void toast(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s.replaceFirst('Exception: ','')))); @override Widget build(c)=>Scaffold(body:SafeArea(child:Padding(padding:const EdgeInsets.all(24),child:ListView(children:[const SizedBox(height:32),const Icon(Icons.shield_outlined,size:64,color:blue),Text(register?'Create your account':'Welcome back',textAlign:TextAlign.center,style:Theme.of(c).textTheme.headlineMedium),const SizedBox(height:24),if(register)field(name,'Name'),field(email,'Email',email:true),field(password,'Password',secret:true),if(register)field(confirm,'Confirm password',secret:true),const SizedBox(height:18),FilledButton(onPressed:busy?null:submit,child:Text(busy?'Please wait...':register?'Create Account':'Login')),TextButton(onPressed:()=>setState(()=>register=!register),child:Text(register?'Already have an account? Login':'New to TrustLens? Register'))])))); Widget field(TextEditingController x,String label,{bool secret=false,bool email=false})=>Padding(padding:const EdgeInsets.only(bottom:12),child:TextField(controller:x,obscureText:secret,keyboardType:email?TextInputType.emailAddress:null,decoration:InputDecoration(labelText:label,border:const OutlineInputBorder())));}
class Dashboard extends StatefulWidget { const Dashboard({super.key,required this.token});final String token;@override State<Dashboard> createState()=>_DashboardState();}
class _DashboardState extends State<Dashboard>{int tab=0;List<dynamic> history=[];bool loading=true;@override void initState(){super.initState();load();}Future<void>load()async{try{history=await Api(widget.token).request('GET','/api/history');}catch(_){ }if(mounted)setState(()=>loading=false);} @override Widget build(c){final pages=[home(),Scanner(token:widget.token,onSaved:load),History(token:widget.token,items:history,onChanged:load),Profile(token:widget.token)];return Scaffold(body:SafeArea(child:pages[tab]),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(v)=>setState(()=>tab=v),destinations:const[NavigationDestination(icon:Icon(Icons.dashboard_outlined),label:'Home'),NavigationDestination(icon:Icon(Icons.document_scanner_outlined),label:'Scan'),NavigationDestination(icon:Icon(Icons.history),label:'History'),NavigationDestination(icon:Icon(Icons.person_outline),label:'Profile')]));} Widget home(){final high=history.where((x)=>x['risk_level']=='HIGH').length,med=history.where((x)=>x['risk_level']=='MEDIUM').length;return Padding(padding:const EdgeInsets.all(20),child:ListView(children:[const Text('TrustLens',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold)),const Text('Your social engineering shield'),const SizedBox(height:20),Wrap(spacing:10,runSpacing:10,children:[stat('Total scans',history.length,blue),stat('High risk',high,Colors.red),stat('Medium',med,Colors.orange)]),const SizedBox(height:24),Text('Recent scans',style:Theme.of(context).textTheme.titleLarge),if(loading)const LinearProgressIndicator(),...history.take(4).map((x)=>Card(child:ListTile(title:Text(x['message'],maxLines:1,overflow:TextOverflow.ellipsis),subtitle:Text(x['risk_level']),trailing:Text('${x['trust_score']}'))))]));} Widget stat(String label,int value,Color color)=>SizedBox(width:105,child:Card(color:color.withValues(alpha:.16),child:Padding(padding:const EdgeInsets.all(14),child:Column(children:[Text('$value',style:TextStyle(fontSize:25,fontWeight:FontWeight.bold,color:color)),Text(label,textAlign:TextAlign.center)]))));}
class Scanner extends StatefulWidget{const Scanner({super.key,required this.token,required this.onSaved});final String token;final Future<void> Function() onSaved;@override State<Scanner>createState()=>_ScannerState();}
class _ScannerState extends State<Scanner>{final text=TextEditingController();String type='sms';bool busy=false;final demos={'High risk':'URGENT! Your bank account will be blocked within 2 hours. Click this link immediately to verify your account.','Medium risk':'Congratulations! You have been selected for a special reward. Contact us immediately to claim your reward.','Low risk':'Hi, our project meeting is scheduled tomorrow at 10 AM. Please bring your laptop.'};Future<void>scan()async{if(text.text.trim().isEmpty)return;setState(()=>busy=true);try{final r=await Api(widget.token).request('POST','/api/analyze',{'message':text.text,'source_type':type});await widget.onSaved();if(mounted)Navigator.push(context,MaterialPageRoute(builder:(_)=>Result(scan:r)));}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString())));}finally{if(mounted)setState(()=>busy=false);}}@override Widget build(c)=>Padding(padding:const EdgeInsets.all(20),child:ListView(children:[Text('Scan message',style:Theme.of(c).textTheme.headlineMedium),const SizedBox(height:12),Wrap(spacing:8,children:['sms','email','chat'].map((x)=>ChoiceChip(label:Text(x.toUpperCase()),selected:type==x,onSelected:(_)=>setState(()=>type=x))).toList()),const SizedBox(height:12),TextField(controller:text,maxLines:9,maxLength:10000,onChanged:(_)=>setState((){}),decoration:const InputDecoration(hintText:'Paste or type a message…',border:OutlineInputBorder())),Text('${text.text.length} characters'),Wrap(spacing:8,children:demos.entries.map((e)=>ActionChip(label:Text(e.key),onPressed:()=>setState(()=>text.text=e.value))).toList()),const SizedBox(height:16),FilledButton.icon(onPressed:busy?null:scan,icon:const Icon(Icons.shield_outlined),label:Text(busy?'Analyzing message...':'Analyze Message')),TextButton(onPressed:()=>setState(text.clear),child:const Text('Clear message'))]));}
class Result extends StatelessWidget {
  const Result({super.key, required this.scan});
  final dynamic scan;
  Color get color => scan['risk_level']=='HIGH' ? Colors.red : scan['risk_level']=='MEDIUM' ? Colors.orange : Colors.green;
  @override Widget build(BuildContext context) {
    final techniques = scan['detected_techniques'] as List;
    return Scaffold(appBar:AppBar(title:const Text('Analysis result')), body:ListView(padding:const EdgeInsets.all(20), children:[
      Card(color:color.withValues(alpha:.14), child:Padding(padding:const EdgeInsets.all(24), child:Column(children:[
        Text('${scan['trust_score']}',style:TextStyle(fontSize:64,fontWeight:FontWeight.bold,color:color)), const Text('TRUST SCORE'), Chip(label:Text(scan['risk_level']),backgroundColor:color)
      ]))), const SizedBox(height:14), Text('WHY IS THIS RISKY?',style:Theme.of(context).textTheme.titleLarge), Text(scan['explanation']), const SizedBox(height:14),
      Text('Detected techniques',style:Theme.of(context).textTheme.titleLarge),
      ...techniques.map((technique) => Card(child:ListTile(leading:Icon(Icons.warning_amber_rounded,color:color),title:Text(technique['name']),subtitle:Text(technique['explanation']),trailing:Text(technique['severity'].toUpperCase())))),
      const SizedBox(height:14), Text('RECOMMENDED ACTION',style:Theme.of(context).textTheme.titleLarge), Text(scan['recommendation'])
    ]));
  }
}
class History extends StatelessWidget{const History({super.key,required this.token,required this.items,required this.onChanged});final String token;final List<dynamic>items;final Future<void>Function()onChanged;@override Widget build(c)=>Padding(padding:const EdgeInsets.all(20),child:ListView(children:[Text('History',style:Theme.of(c).textTheme.headlineMedium),if(items.isEmpty)const Padding(padding:EdgeInsets.all(30),child:Text('No scans yet.')), ...items.map((x)=>Card(child:ListTile(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>Result(scan:x))),title:Text(x['message'],maxLines:2,overflow:TextOverflow.ellipsis),subtitle:Text('${x['risk_level']} • ${x['created_at']}'),trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:()async{await Api(token).request('DELETE','/api/history/${x['id']}');await onChanged();}))))]));}
class Profile extends StatelessWidget{const Profile({super.key,required this.token});final String token;@override Widget build(c)=>Padding(padding:const EdgeInsets.all(20),child:ListView(children:[Text('Profile',style:Theme.of(c).textTheme.headlineMedium),const CircleAvatar(radius:36,child:Icon(Icons.person,size:36)),const SizedBox(height:20),FutureBuilder(future:Api(token).request('GET','/api/auth/me'),builder:(c,s)=>Card(child:ListTile(title:Text(s.hasData?s.data['name']:'Loading…'),subtitle:Text(s.hasData?s.data['email']:'')))),const SizedBox(height:12),OutlinedButton.icon(onPressed:()async{await const FlutterSecureStorage().delete(key:'token');if(c.mounted)Navigator.pushAndRemoveUntil(c,MaterialPageRoute(builder:(_)=>const AuthPage()),(_)=>false);},icon:const Icon(Icons.logout),label:const Text('Logout'))]));}
